/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ReputationRegistry {
  export type ReputationStruct = {
    totalSignals: BigNumberish;
    settledSignals: BigNumberish;
    accurateSignals: BigNumberish;
    cumulativePnlBps: BigNumberish;
    reputationScore: BigNumberish;
  };

  export type ReputationStructOutput = [
    totalSignals: bigint,
    settledSignals: bigint,
    accurateSignals: bigint,
    cumulativePnlBps: bigint,
    reputationScore: bigint
  ] & {
    totalSignals: bigint;
    settledSignals: bigint;
    accurateSignals: bigint;
    cumulativePnlBps: bigint;
    reputationScore: bigint;
  };

  export type SettlementRecordStruct = {
    agent: AddressLike;
    accurate: boolean;
    pnlBps: BigNumberish;
    signalId: BigNumberish;
    recordedAt: BigNumberish;
    reputationScore: BigNumberish;
  };

  export type SettlementRecordStructOutput = [
    agent: string,
    accurate: boolean,
    pnlBps: bigint,
    signalId: bigint,
    recordedAt: bigint,
    reputationScore: bigint
  ] & {
    agent: string;
    accurate: boolean;
    pnlBps: bigint;
    signalId: bigint;
    recordedAt: bigint;
    reputationScore: bigint;
  };
}

export interface ReputationRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getReputation"
      | "getScore"
      | "getSettlement"
      | "owner"
      | "recordSettlement"
      | "renounceOwnership"
      | "scorer"
      | "setScorer"
      | "signalRecorded"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "ReputationUpdated"
      | "ScorerUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getReputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSettlement",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordSettlement",
    values: [AddressLike, boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "scorer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setScorer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "signalRecorded",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getScore", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSettlement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordSettlement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "scorer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setScorer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "signalRecorded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationUpdatedEvent {
  export type InputTuple = [
    agent: AddressLike,
    reputationScore: BigNumberish,
    totalSignals: BigNumberish
  ];
  export type OutputTuple = [
    agent: string,
    reputationScore: bigint,
    totalSignals: bigint
  ];
  export interface OutputObject {
    agent: string;
    reputationScore: bigint;
    totalSignals: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScorerUpdatedEvent {
  export type InputTuple = [scorer: AddressLike];
  export type OutputTuple = [scorer: string];
  export interface OutputObject {
    scorer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReputationRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ReputationRegistry;
  waitForDeployment(): Promise<this>;

  interface: ReputationRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getReputation: TypedContractMethod<
    [agent: AddressLike],
    [ReputationRegistry.ReputationStructOutput],
    "view"
  >;

  getScore: TypedContractMethod<[agent: AddressLike], [bigint], "view">;

  getSettlement: TypedContractMethod<
    [signalId: BigNumberish],
    [ReputationRegistry.SettlementRecordStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  recordSettlement: TypedContractMethod<
    [
      agent: AddressLike,
      accurate: boolean,
      pnlBps: BigNumberish,
      signalId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  scorer: TypedContractMethod<[], [string], "view">;

  setScorer: TypedContractMethod<
    [newScorer: AddressLike],
    [void],
    "nonpayable"
  >;

  signalRecorded: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getReputation"
  ): TypedContractMethod<
    [agent: AddressLike],
    [ReputationRegistry.ReputationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getScore"
  ): TypedContractMethod<[agent: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSettlement"
  ): TypedContractMethod<
    [signalId: BigNumberish],
    [ReputationRegistry.SettlementRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordSettlement"
  ): TypedContractMethod<
    [
      agent: AddressLike,
      accurate: boolean,
      pnlBps: BigNumberish,
      signalId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "scorer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setScorer"
  ): TypedContractMethod<[newScorer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "signalRecorded"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReputationUpdated"
  ): TypedContractEvent<
    ReputationUpdatedEvent.InputTuple,
    ReputationUpdatedEvent.OutputTuple,
    ReputationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ScorerUpdated"
  ): TypedContractEvent<
    ScorerUpdatedEvent.InputTuple,
    ScorerUpdatedEvent.OutputTuple,
    ScorerUpdatedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReputationUpdated(address,uint256,uint256)": TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
    ReputationUpdated: TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;

    "ScorerUpdated(address)": TypedContractEvent<
      ScorerUpdatedEvent.InputTuple,
      ScorerUpdatedEvent.OutputTuple,
      ScorerUpdatedEvent.OutputObject
    >;
    ScorerUpdated: TypedContractEvent<
      ScorerUpdatedEvent.InputTuple,
      ScorerUpdatedEvent.OutputTuple,
      ScorerUpdatedEvent.OutputObject
    >;
  };
}
