/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SignalRegistry {
  export type SignalStruct = {
    signalHash: BytesLike;
    agent: AddressLike;
    expiration: BigNumberish;
    committedAt: BigNumberish;
    stakeAmount: BigNumberish;
    status: BigNumberish;
    accurate: boolean;
    pnlBps: BigNumberish;
  };

  export type SignalStructOutput = [
    signalHash: string,
    agent: string,
    expiration: bigint,
    committedAt: bigint,
    stakeAmount: bigint,
    status: bigint,
    accurate: boolean,
    pnlBps: bigint
  ] & {
    signalHash: string;
    agent: string;
    expiration: bigint;
    committedAt: bigint;
    stakeAmount: bigint;
    status: bigint;
    accurate: boolean;
    pnlBps: bigint;
  };
}

export interface SignalRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentSignals"
      | "commitSignal"
      | "getAgentSignalCount"
      | "getAgentSignalIds"
      | "getSignal"
      | "hashCommitted"
      | "markExpired"
      | "minStake"
      | "nextSignalId"
      | "owner"
      | "renounceOwnership"
      | "setMinStake"
      | "setSettler"
      | "settleSignal"
      | "settler"
      | "signals"
      | "transferOwnership"
      | "withdrawFunds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FundsWithdrawn"
      | "MinStakeUpdated"
      | "OwnershipTransferred"
      | "SettlerUpdated"
      | "SignalCommitted"
      | "SignalExpired"
      | "SignalSettled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentSignals",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "commitSignal",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentSignalCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentSignalIds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSignal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hashCommitted",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markExpired",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "minStake", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nextSignalId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMinStake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSettler",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settleSignal",
    values: [BigNumberish, boolean, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "settler", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "signals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFunds",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "agentSignals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitSignal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentSignalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentSignalIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSignal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hashCommitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markExpired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "minStake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextSignalId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setSettler", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "settleSignal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settler", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "signals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFunds",
    data: BytesLike
  ): Result;
}

export namespace FundsWithdrawnEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinStakeUpdatedEvent {
  export type InputTuple = [newMinStake: BigNumberish];
  export type OutputTuple = [newMinStake: bigint];
  export interface OutputObject {
    newMinStake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettlerUpdatedEvent {
  export type InputTuple = [newSettler: AddressLike];
  export type OutputTuple = [newSettler: string];
  export interface OutputObject {
    newSettler: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignalCommittedEvent {
  export type InputTuple = [
    signalId: BigNumberish,
    agent: AddressLike,
    signalHash: BytesLike,
    expiration: BigNumberish,
    stakeAmount: BigNumberish
  ];
  export type OutputTuple = [
    signalId: bigint,
    agent: string,
    signalHash: string,
    expiration: bigint,
    stakeAmount: bigint
  ];
  export interface OutputObject {
    signalId: bigint;
    agent: string;
    signalHash: string;
    expiration: bigint;
    stakeAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignalExpiredEvent {
  export type InputTuple = [signalId: BigNumberish];
  export type OutputTuple = [signalId: bigint];
  export interface OutputObject {
    signalId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignalSettledEvent {
  export type InputTuple = [
    signalId: BigNumberish,
    agent: AddressLike,
    accurate: boolean,
    pnlBps: BigNumberish
  ];
  export type OutputTuple = [
    signalId: bigint,
    agent: string,
    accurate: boolean,
    pnlBps: bigint
  ];
  export interface OutputObject {
    signalId: bigint;
    agent: string;
    accurate: boolean;
    pnlBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SignalRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): SignalRegistry;
  waitForDeployment(): Promise<this>;

  interface: SignalRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentSignals: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  commitSignal: TypedContractMethod<
    [signalHash: BytesLike, expiration: BigNumberish],
    [bigint],
    "payable"
  >;

  getAgentSignalCount: TypedContractMethod<
    [agent: AddressLike],
    [bigint],
    "view"
  >;

  getAgentSignalIds: TypedContractMethod<
    [agent: AddressLike],
    [bigint[]],
    "view"
  >;

  getSignal: TypedContractMethod<
    [signalId: BigNumberish],
    [SignalRegistry.SignalStructOutput],
    "view"
  >;

  hashCommitted: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  markExpired: TypedContractMethod<
    [signalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  minStake: TypedContractMethod<[], [bigint], "view">;

  nextSignalId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setMinStake: TypedContractMethod<
    [newMinStake: BigNumberish],
    [void],
    "nonpayable"
  >;

  setSettler: TypedContractMethod<
    [newSettler: AddressLike],
    [void],
    "nonpayable"
  >;

  settleSignal: TypedContractMethod<
    [signalId: BigNumberish, accurate: boolean, pnlBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  settler: TypedContractMethod<[], [string], "view">;

  signals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean, bigint] & {
        signalHash: string;
        agent: string;
        expiration: bigint;
        committedAt: bigint;
        stakeAmount: bigint;
        status: bigint;
        accurate: boolean;
        pnlBps: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawFunds: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentSignals"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "commitSignal"
  ): TypedContractMethod<
    [signalHash: BytesLike, expiration: BigNumberish],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getAgentSignalCount"
  ): TypedContractMethod<[agent: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAgentSignalIds"
  ): TypedContractMethod<[agent: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getSignal"
  ): TypedContractMethod<
    [signalId: BigNumberish],
    [SignalRegistry.SignalStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hashCommitted"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "markExpired"
  ): TypedContractMethod<[signalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "minStake"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextSignalId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinStake"
  ): TypedContractMethod<[newMinStake: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSettler"
  ): TypedContractMethod<[newSettler: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settleSignal"
  ): TypedContractMethod<
    [signalId: BigNumberish, accurate: boolean, pnlBps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settler"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "signals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean, bigint] & {
        signalHash: string;
        agent: string;
        expiration: bigint;
        committedAt: bigint;
        stakeAmount: bigint;
        status: bigint;
        accurate: boolean;
        pnlBps: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFunds"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "FundsWithdrawn"
  ): TypedContractEvent<
    FundsWithdrawnEvent.InputTuple,
    FundsWithdrawnEvent.OutputTuple,
    FundsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "MinStakeUpdated"
  ): TypedContractEvent<
    MinStakeUpdatedEvent.InputTuple,
    MinStakeUpdatedEvent.OutputTuple,
    MinStakeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SettlerUpdated"
  ): TypedContractEvent<
    SettlerUpdatedEvent.InputTuple,
    SettlerUpdatedEvent.OutputTuple,
    SettlerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SignalCommitted"
  ): TypedContractEvent<
    SignalCommittedEvent.InputTuple,
    SignalCommittedEvent.OutputTuple,
    SignalCommittedEvent.OutputObject
  >;
  getEvent(
    key: "SignalExpired"
  ): TypedContractEvent<
    SignalExpiredEvent.InputTuple,
    SignalExpiredEvent.OutputTuple,
    SignalExpiredEvent.OutputObject
  >;
  getEvent(
    key: "SignalSettled"
  ): TypedContractEvent<
    SignalSettledEvent.InputTuple,
    SignalSettledEvent.OutputTuple,
    SignalSettledEvent.OutputObject
  >;

  filters: {
    "FundsWithdrawn(address,uint256)": TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;
    FundsWithdrawn: TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;

    "MinStakeUpdated(uint256)": TypedContractEvent<
      MinStakeUpdatedEvent.InputTuple,
      MinStakeUpdatedEvent.OutputTuple,
      MinStakeUpdatedEvent.OutputObject
    >;
    MinStakeUpdated: TypedContractEvent<
      MinStakeUpdatedEvent.InputTuple,
      MinStakeUpdatedEvent.OutputTuple,
      MinStakeUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SettlerUpdated(address)": TypedContractEvent<
      SettlerUpdatedEvent.InputTuple,
      SettlerUpdatedEvent.OutputTuple,
      SettlerUpdatedEvent.OutputObject
    >;
    SettlerUpdated: TypedContractEvent<
      SettlerUpdatedEvent.InputTuple,
      SettlerUpdatedEvent.OutputTuple,
      SettlerUpdatedEvent.OutputObject
    >;

    "SignalCommitted(uint256,address,bytes32,uint256,uint256)": TypedContractEvent<
      SignalCommittedEvent.InputTuple,
      SignalCommittedEvent.OutputTuple,
      SignalCommittedEvent.OutputObject
    >;
    SignalCommitted: TypedContractEvent<
      SignalCommittedEvent.InputTuple,
      SignalCommittedEvent.OutputTuple,
      SignalCommittedEvent.OutputObject
    >;

    "SignalExpired(uint256)": TypedContractEvent<
      SignalExpiredEvent.InputTuple,
      SignalExpiredEvent.OutputTuple,
      SignalExpiredEvent.OutputObject
    >;
    SignalExpired: TypedContractEvent<
      SignalExpiredEvent.InputTuple,
      SignalExpiredEvent.OutputTuple,
      SignalExpiredEvent.OutputObject
    >;

    "SignalSettled(uint256,address,bool,int256)": TypedContractEvent<
      SignalSettledEvent.InputTuple,
      SignalSettledEvent.OutputTuple,
      SignalSettledEvent.OutputObject
    >;
    SignalSettled: TypedContractEvent<
      SignalSettledEvent.InputTuple,
      SignalSettledEvent.OutputTuple,
      SignalSettledEvent.OutputObject
    >;
  };
}
