/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SignalRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "commitSignal"
      | "getAgentSignalCount"
      | "getAgentSignalIds"
      | "getSignal"
      | "hashCommitted"
      | "nextSignalId"
      | "revealSignal"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "SignalCommitted" | "SignalRevealed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "commitSignal",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentSignalCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentSignalIds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSignal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hashCommitted",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextSignalId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revealSignal",
    values: [BigNumberish, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "commitSignal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentSignalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentSignalIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSignal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hashCommitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextSignalId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revealSignal",
    data: BytesLike
  ): Result;
}

export namespace SignalCommittedEvent {
  export type InputTuple = [
    signalId: BigNumberish,
    agent: AddressLike,
    hash: BytesLike,
    expiration: BigNumberish
  ];
  export type OutputTuple = [
    signalId: bigint,
    agent: string,
    hash: string,
    expiration: bigint
  ];
  export interface OutputObject {
    signalId: bigint;
    agent: string;
    hash: string;
    expiration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignalRevealedEvent {
  export type InputTuple = [
    signalId: BigNumberish,
    agent: AddressLike,
    rawPayload: string
  ];
  export type OutputTuple = [
    signalId: bigint,
    agent: string,
    rawPayload: string
  ];
  export interface OutputObject {
    signalId: bigint;
    agent: string;
    rawPayload: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SignalRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): SignalRegistry;
  waitForDeployment(): Promise<this>;

  interface: SignalRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  commitSignal: TypedContractMethod<
    [hash: BytesLike, expiration: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getAgentSignalCount: TypedContractMethod<
    [agent: AddressLike],
    [bigint],
    "view"
  >;

  getAgentSignalIds: TypedContractMethod<
    [agent: AddressLike],
    [bigint[]],
    "view"
  >;

  getSignal: TypedContractMethod<
    [id: BigNumberish],
    [
      [string, string, bigint, bigint, boolean] & {
        hash: string;
        agent: string;
        committedAt: bigint;
        expiration: bigint;
        revealed: boolean;
      }
    ],
    "view"
  >;

  hashCommitted: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  nextSignalId: TypedContractMethod<[], [bigint], "view">;

  revealSignal: TypedContractMethod<
    [onChainId: BigNumberish, rawPayload: string, salt: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "commitSignal"
  ): TypedContractMethod<
    [hash: BytesLike, expiration: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAgentSignalCount"
  ): TypedContractMethod<[agent: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAgentSignalIds"
  ): TypedContractMethod<[agent: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getSignal"
  ): TypedContractMethod<
    [id: BigNumberish],
    [
      [string, string, bigint, bigint, boolean] & {
        hash: string;
        agent: string;
        committedAt: bigint;
        expiration: bigint;
        revealed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hashCommitted"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "nextSignalId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "revealSignal"
  ): TypedContractMethod<
    [onChainId: BigNumberish, rawPayload: string, salt: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "SignalCommitted"
  ): TypedContractEvent<
    SignalCommittedEvent.InputTuple,
    SignalCommittedEvent.OutputTuple,
    SignalCommittedEvent.OutputObject
  >;
  getEvent(
    key: "SignalRevealed"
  ): TypedContractEvent<
    SignalRevealedEvent.InputTuple,
    SignalRevealedEvent.OutputTuple,
    SignalRevealedEvent.OutputObject
  >;

  filters: {
    "SignalCommitted(uint256,address,bytes32,uint256)": TypedContractEvent<
      SignalCommittedEvent.InputTuple,
      SignalCommittedEvent.OutputTuple,
      SignalCommittedEvent.OutputObject
    >;
    SignalCommitted: TypedContractEvent<
      SignalCommittedEvent.InputTuple,
      SignalCommittedEvent.OutputTuple,
      SignalCommittedEvent.OutputObject
    >;

    "SignalRevealed(uint256,address,string)": TypedContractEvent<
      SignalRevealedEvent.InputTuple,
      SignalRevealedEvent.OutputTuple,
      SignalRevealedEvent.OutputObject
    >;
    SignalRevealed: TypedContractEvent<
      SignalRevealedEvent.InputTuple,
      SignalRevealedEvent.OutputTuple,
      SignalRevealedEvent.OutputObject
    >;
  };
}
